config/routes.rb
Rails.application.routes.draw do
  resources :series
  resources :ebooks
  require 'sidekiq/web'

  authenticate :user, ->(user) { user.admin_role? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  namespace :admin do
    #get "dashboard", to: "dashboard#index"
    resources :publishers
    resources :users
    resources :categories do
      post :move, on: :member
      get :cancel, on: :member
      get :item, on: :member
    end
    root to: 'dashboard#index'
  end

  get '/profil', to: 'users#profile', as: :profile
  devise_for :users
  resources :users, only: %i(update) do
    patch :update_password, on: :member
  end

  resources :publishers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  resources :language, only: [:index, :show]
  resources :authors
  # Defines the root path route ("/")
  root to: 'home#index'
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  include Active
  has_rich_text :content

  has_many :ebooks, dependent: :nullify
  has_many :users, dependent: :nullify
  validates :url, uniqueness: true
  validates :title, presence: true
  validates :email, uniqueness: true, presence: true

  scope :ordered_by, ->(column, direction = 'asc') {
    allowed_columns = column_names.map(&:to_s) # Získá seznam povolených sloupců

    column = allowed_columns.include?(column.to_s) ? column.to_sym : 'id' # Ověření sloupce
    direction = %w[asc desc].include?(direction) ? direction : 'asc' # Ověření směru

    order(column => Arel.sql(direction)) # Použití Arel.sql() jen pro směrování
  }
  scope :search, ->(query) {
    where("LOWER(title) LIKE unaccent(:query) OR LOWER(url) LIKE unaccent(:query) OR LOWER(address) LIKE unaccent(:query) OR LOWER(email) LIKE unaccent(:query)", query: "%#{query.downcase}%")
  }
end

app/controllers/admin/publisher_controller.rb
class Admin::PublisherController < ApplicationController
  def index
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/admin/publishers_controller.rb
class Admin::PublishersController < ApplicationController
  def index
    authorize Publisher
    @publishers = Publisher.all
    @publishers = @publishers.search(params[:query]) if params[:query].present?
    @publishers = @publishers.ordered_by(params[:order], params[:direction]).page(params[:page]).per(per_page).decorate
    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def new
    @publisher = Publisher.new
    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def create
    creator = Publishers::Creator.call(publisher_params, user_params)
    if creator.success?
      @publisher = creator.result.decorate
      respond_to do |format|
        format.html { redirect_to admin_publishers_path, notice: t('views.admin.publishers.create_success') }
        format.turbo_stream
      end
    else
      @errors = creator.errors
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
        format.turbo_stream
      end
    end
  end

  def show
  end

  def edit
    @publisher = Publisher.find(params[:id])
  end

  def update
    updator = Publishers::Updator.call(params[:id], publisher_params)
    if updator.success?
      @publisher = updator.result.decorate
      respond_to do |format|
        format.html { redirect_to admin_publishers_path, notice: t('views.admin.publishers.update_success') }
        format.turbo_stream
      end
    else
      @errors = updator.errors
      respond_to do |format|
        format.html { render :edit, status: :unprocessable_entity }
        format.turbo_stream
      end
    end
  end

  def destroy
  end

  private

  def user_params
    params.require(:publisher).require(:user).permit(:first_name, :last_name)
  end

  def publisher_params
    params.require(:publisher).permit(:title, :content, :address, :url, :email, :active)
  end

  def per_page
    params[:per_page] || PublisherDecorator::PER_PAGES_DEFAULT
  end
end

app/helpers/admin/publisher_helper.rb
module Admin::PublisherHelper
  def publisher_sort_link(column, label)
    direction = params[:order] == column && params[:direction] == 'asc' ? 'desc' : 'asc'
    icon = params[:order] == column ? (params[:direction] == 'asc' ? '▲' : '▼') : ''
    query = params[:query] || ''

    link_to "#{label} #{icon}".html_safe, admin_publishers_path(order: column, direction: direction, query: query),
            data: { turbo_frame: 'result', turbo_stream: 'update' }, class: 'sort-link'
  end
end

app/helpers/admin/publishers_helper.rb
module Admin::PublishersHelper
end

app/views/admin/publishers/_errors.html.erb
<% if errors.present? %>
  <div class="notification red" data-dismiss-target="notification" data-controller="dismiss">
    <div class="flex flex-col md:flex-row items-center justify-between space-y-3 md:space-y-0">
      <div>
        <ul>
          <% errors.keys.each do |attribute| %>
            <% if errors[attribute].any? %>
              <li>
                <strong><%= t("views.admin.publishers.errors.#{attribute.to_s}") %>:</strong>
                <% errors[attribute].each do |message| %>
                  <ul>
                    <li><%= message %></li>
                  </ul>
                <% end %>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
      <%= button_tag t('helpers.submit.close'), type: "button", class: "button small textual",
        data: { action: "dismiss#dismiss" } %>
    </div>
  </div>
<% end %>

app/views/admin/publishers/_form.html.erb
<%= turbo_frame_tag 'publisher_notice' %>
<section class="section main-section" data-controller="fade-out" data-fade-out-target="frame" data-auto-fade-out-target="frame">
  <div class="card mb-6">
    <header class="card-header">
      <p class="card-header-title">
        <span class="icon"><i class="mdi mdi-ballot"></i></span>
        <%= @publisher.persisted? ? t('views.admin.publishers.edit.title') : t('views.admin.publishers.new.title') %>
      </p>
    </header>
    <div class="card-content">
      <%= turbo_frame_tag 'publisher_errors' do %>
        <%= render partial: 'admin/publishers/errors', locals: { errors: @errors } if @errors.present? %>
      <% end %>
      <%= form_with model: @publisher, url: @publisher.persisted? ? admin_publisher_path(@publisher) : admin_publishers_path,
                    data: { turbo: @turbo_request } do |f| %>
        <div class="field">
          <%= f.label :title, class: "label" %>
          <div class="control">
            <%= f.text_field :title, class: "input", placeholder: t('activerecord.attributes.publisher.title') %>
          </div>
        </div>

        <div class="field">
          <%= f.label :address, class: "label" %>
          <div class="control">
            <%= f.text_field :address, class: "input", placeholder: t('activerecord.attributes.publisher.address') %>
          </div>
        </div>

        <div class="field">
          <%= f.label :url, class: "label" %>
          <div class="control">
            <%= f.text_field :url, class: "input", placeholder: t('activerecord.attributes.publisher.url') %>
          </div>
        </div>

        <div class="field">
          <%= f.label :email, class: "label" %>
          <div class="control icons-left">
            <%= f.email_field :email, class: "input", placeholder: t('activerecord.attributes.publisher.email'),
              value: @publisher.email %>
            <span class="icon left"><i class="mdi mdi-mail"></i></span>
          </div>
        </div>

        <div class="field">
          <%= f.label :active, class: "label" %>
          <div class="control">
            <%= f.check_box :active, class: "checkbox" %>
          </div>
        </div>

        <div class="field">
          <%= f.label :content, class: "label" %>
          <div class="control">
            <%= f.rich_text_area :content, class: "textarea",
              placeholder: t('activerecord.attributes.publisher.content'), data: { controller: 'trix' } %>
          </div>
        </div>
        <% unless @publisher.persisted? %>
          <fieldset>
            <div class="field">
              <p>
                <strong><%= t('views.admin.publishers.new.user_name') %></strong>
                <small><%= t('views.admin.publishers.new.user_name_title') %></small>
              </p>
            </div>

            <div class="field">
              <%= f.fields_for :user do |user_fields| %>
                <div class="field">
                  <%= user_fields.label :first_name, t('activerecord.attributes.user.first_name'), class: "label" %>
                  <div class="control">
                    <%= user_fields.text_field :first_name, class: "input",
                      placeholder: t('activerecord.attributes.user.first_name') %>
                  </div>
                </div>

                <div class="field">
                  <%= user_fields.label :last_name, t('activerecord.attributes.user.last_name'), class: "label" %>
                  <div class="control">
                    <%= user_fields.text_field :last_name, class: "input",
                      placeholder: t('activerecord.attributes.user.last_name') %>
                  </div>
                </div>
              <% end %>
            </div>
          </fieldset>
        <% end %>
        <hr>

        <div class="field grouped">
          <div class="control">
            <%= f.submit @publisher.persisted? ? t('views.admin.publishers.edit.submit') : t('views.admin.publishers.new.submit'), class: "button green" %>
          </div>
          <div class="control">
            <% if @turbo_request %>
              <%= button_tag t('helpers.submit.cancel'), type: "reset", class: "button",
                             data: { action: "fade-out#remove" } %>
            <% else %>
              <%= link_to t('helpers.submit.cancel'), admin_publishers_path, class: "button", data: { turbo_frame: "_top" } %>
            <% end %>
          </div>
        </div>

      <% end %>
    </div>
  </div>
</section>

app/views/admin/publishers/_index.html.erb
<div class="card has-table">
  <header class="card-header">
    <p class="card-header-title">
      <span class="icon"><i class="mdi mdi-account-multiple"></i></span><%= t('views.admin.publishers.title') %>
      &nbsp;&nbsp;
      <%= link_to new_admin_publisher_path, class: "button small blue", title: t('views.admin.publishers.new_button'),
                  data: { turbo_frame: "publisher_form", turbo_stream: 'update' } do %>
        <span class="icon"><i class="mdi mdi-plus"></i></span>
      <% end %>
    </p>
    <%= form_with url: admin_publishers_path, method: :get, data: { controller: 'search-form', turbo_frame: 'result',
                                                                    turbo_stream: 'update' },
                  class: "control has-icons-left" do |f| %>
      <div class="field">
        <div class="field-body">
          <div class="field">
            <div class="control icons-left">
              <%= f.text_field :query, placeholder: t('helpers.placeholder.search'), class: "input",
                               data: { "search-form-target": 'input', action: 'keyup->search-form#handleKeyup' } %>
              <span class="icon left"><i class="mdi mdi-magnify"></i></span>
            </div>
          </div>
        </div>
      </div>
    <% end %>

    <a href="#" class="card-header-icon">
      <span class="icon"><i class="mdi mdi-reload"></i></span>
    </a>
  </header>
  <div class="card-content">
    <%= turbo_frame_tag 'results' do %>
      <%= render partial: 'admin/publishers/publishers' %>
    <% end %>
  </div>
</div>

app/views/admin/publishers/_publisher.html.erb
<tr id="publisher_<%= publisher.id %>" class="<%= 'highlight' if local_assigns[:highlight] %>">
  <%= render partial: 'admin/publishers/publisher_items', locals: { publisher: publisher } %>
</tr>

app/views/admin/publishers/_publisher_items.html.erb
<td data-label="name"><%= publisher.title %></td>
<td data-label="email"><%= publisher.email %></td>
<td data-label="address"><%= publisher.address_trim %></td>
<td data-label="url"><%= publisher.url %></td>
<td data-label="active">
  <%= content_tag(:i, "", class: "mdi #{publisher.active ? 'mdi-check-circle text-green-500' : 'mdi-close-circle text-red-500'}") %>
</td>
<td class="actions-cell">
  <div class="buttons right nowrap">
    <button class="button small blue --jb-modal"  data-target="sample-modal-2" type="button">
      <span class="icon"><i class="mdi mdi-eye"></i></span>
    </button>
    <%= link_to edit_admin_publisher_path(publisher), class: "button small green", title: t('views.admin.publishers.edit_button'),
                data: { turbo_frame: "publisher_form", turbo_stream: 'update' } do %>
      <span class="icon"><i class="mdi mdi-pencil"></i></span>
    <% end %>
    <!--
    <button class="button small red --jb-modal" data-target="sample-modal" type="button">
      <span class="icon"><i class="mdi mdi-trash-can"></i></span>
    </button>-->
  </div>
</td>

app/views/admin/publishers/_publishers.html.erb
<% if @publishers.any? %>
  <%= paginate @publishers %>
  <table>
    <thead>
    <tr>
      <th><%= publisher_sort_link('title', t('activerecord.attributes.publisher.title')) %></th>
      <th><%= publisher_sort_link('email', t('activerecord.attributes.publisher.email')) %></th>
      <th><%= publisher_sort_link('address', t('activerecord.attributes.publisher.address')) %></th>
      <th><%= publisher_sort_link('url', t('activerecord.attributes.publisher.url')) %></th>
      <th><%= publisher_sort_link('active', t('activerecord.attributes.publisher.active')) %></th>
      <th></th>
    </tr>
    </thead>
    <tbody id="publishers-list">
    <% @publishers.each do |publisher| %>
      <%= render partial: 'admin/publishers/publisher', locals: { publisher: publisher } %>
    <% end %>
    </tbody>
  </table>
  <%= paginate @publishers %>
<% else %>
  <p class="padding-10"><%= t('views.admin.publishers.no_publishers') %></p>
<% end %>

app/views/admin/publishers/create.turbo_stream.erb
<% if @errors.present? %>
  <%= turbo_stream.update 'publisher_errors', partial: 'admin/publishers/errors', locals: { errors: @errors } %>
<% else %>
  <%= turbo_stream.update "publisher_notice", partial: 'shared/notice', locals: { notice: t('views.admin.publishers.create_success') } %>
  <%= turbo_stream.prepend "publisher_notice" do %>
    <div data-controller="auto-fade-out" ></div>
  <% end %>
  <%= turbo_stream.prepend "publishers-list" do %>
    <%= render @publisher, highlight: true %>
  <% end %>
<% end %>

app/views/admin/publishers/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">Admin::Publishers#destroy</h1>
  <p>Find me in app/views/admin/publishers/destroy.html.erb</p>
</div>

app/views/admin/publishers/index.html.erb
<%= render 'layouts/header/admin_navbar' %>
<%= render 'layouts/aside/admin_nav' %>
<section class="is-hero-bar">
  <div class="flex flex-col md:flex-row items-center justify-between space-y-6 md:space-y-0">
    <h1 class="title"><%= t('views.admin.publishers.title') %></h1>
  </div>
</section>
<section class="section main-section">
  <%= turbo_frame_tag "publisher_form", data: { fade_out_target: "frame" } %>
  <%= render 'admin/publishers/index' %>
</section>

app/views/admin/publishers/new.html.erb
<%= render 'layouts/header/admin_navbar' %>
<%= render 'layouts/aside/admin_nav' %>
<section class="is-hero-bar">
  <div class="flex flex-col md:flex-row items-center justify-between space-y-6 md:space-y-0">
    <h1 class="title"><%= t('views.admin.publishers.title') %></h1>
  </div>
</section>
<section class="section main-section">
  <%= turbo_frame_tag "publisher_form" do %>
    <%= render partial: 'admin/publishers/form' %>
  <% end %>
</section>

app/views/admin/publishers/new.turbo_stream.erb
<%= turbo_stream.update 'publisher_form', partial: 'admin/publishers/form' %>

app/views/admin/publishers/show.html.erb
<div>
  <h1 class="font-bold text-4xl">Admin::Publishers#show</h1>
  <p>Find me in app/views/admin/publishers/show.html.erb</p>
</div>

app/views/admin/publishers/update.html.erb
<div>
  <h1 class="font-bold text-4xl">Admin::Publishers#update</h1>
  <p>Find me in app/views/admin/publishers/update.html.erb</p>
</div>

app/views/admin/publishers/update.turbo_stream.erb
<% if @errors.present? %>
  <%= turbo_stream.update 'publisher_errors', partial: 'admin/publishers/errors', locals: { errors: @errors } %>
<% else %>
  <%= turbo_stream.update "publisher_notice", partial: 'shared/notice', locals: { notice: t('views.admin.publishers.update_success') } %>
  <%= turbo_stream.prepend "publisher_notice" do %>
    <div data-controller="auto-fade-out" ></div>
  <% end %>
  <%= turbo_stream.update "publisher_#{@publisher.id}" do %>
    <%= render partial: 'admin/publishers/publisher_items', locals: { publisher: @publisher }, highlight: true %>
  <% end %>
<% end %>