config/routes.rb
Rails.application.routes.draw do
  resources :series
  resources :ebooks
  require 'sidekiq/web'

  authenticate :user, ->(user) { user.admin_role? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  namespace :admin do
    #get "dashboard", to: "dashboard#index"
    resources :publishers
    resources :users
    resources :categories do
      post :move, on: :member
      get :cancel, on: :member
      get :item, on: :member
    end
    root to: 'dashboard#index'
  end

  get '/profil', to: 'users#profile', as: :profile
  devise_for :users
  resources :users, only: %i(update) do
    patch :update_password, on: :member
  end

  resources :publishers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  resources :language, only: [:index, :show]
  resources :authors
  # Defines the root path route ("/")
  root to: 'home#index'
end

app/views/layouts/header/_admin_navbar.html.erb
<nav id="navbar-main" class="navbar is-fixed-top">
  <div class="navbar-brand">
    <a class="navbar-item mobile-aside-button">
      <span class="icon"><i class="mdi mdi-forwardburger mdi-24px"></i></span>
    </a>
    <div class="navbar-item">
      <div class="control"><input placeholder="Search everywhere..." class="input"></div>
    </div>
  </div>
  <div class="navbar-brand is-right">
    <a class="navbar-item --jb-navbar-menu-toggle" data-target="navbar-menu">
      <span class="icon"><i class="mdi mdi-dots-vertical mdi-24px"></i></span>
    </a>
  </div>
  <div class="navbar-menu" id="navbar-menu">
    <div class="navbar-end">
      <div class="navbar-item dropdown has-divider">
        <a class="navbar-link">
          <span class="icon"><i class="mdi mdi-menu"></i></span>
          <span>Sample Menu</span>
          <span class="icon">
            <i class="mdi mdi-chevron-down"></i>
          </span>
        </a>
        <div class="navbar-dropdown">
          <a href="profile.html" class="navbar-item">
            <span class="icon"><i class="mdi mdi-account"></i></span>
            <span>My Profile</span>
          </a>
          <a class="navbar-item">
            <span class="icon"><i class="mdi mdi-settings"></i></span>
            <span>Settings</span>
          </a>
          <a class="navbar-item">
            <span class="icon"><i class="mdi mdi-email"></i></span>
            <span>Messages</span>
          </a>
          <hr class="navbar-divider">
          <%= link_to destroy_user_session_path, method: :delete,
                      title: t('devise.navbar.sign_out'), class: 'navbar-item', turbo_frame: '_top',
                      data: { turbo_method: :delete, turbo_confirm: t('devise.sessions.sure') } do %>
            <span class="icon"><i class="mdi mdi-logout"></i></span>
            <span><%= t('devise.navbar.sign_out') %></span>
          <% end %>
        </div>
      </div>
      <div class="navbar-item dropdown has-divider has-user-avatar">
        <a class="navbar-link">
          <div class="user-avatar">
            <% if current_user.avatar.present? %>
              <%= image_tag current_user.avatar_thumb, class: "rounded-full",
                            alt: "#{current_user.first_name} #{current_user.last_name}" %>
            <% else %>
              <%= image_tag 'no-one.png', class: "rounded-full",
                            alt: "#{current_user.first_name} #{current_user.last_name}" %>
            <% end %>
          </div>
          <div class="is-user-name"><span><%= "#{current_user.first_name} #{current_user.last_name}" %></span></div>
          <span class="icon"><i class="mdi mdi-chevron-down"></i></span>
        </a>
        <div class="navbar-dropdown">
          <a href="profile.html" class="navbar-item">
            <span class="icon"><i class="mdi mdi-account"></i></span>
            <span>My Profile</span>
          </a>
          <a class="navbar-item">
            <span class="icon"><i class="mdi mdi-settings"></i></span>
            <span>Settings</span>
          </a>
          <a class="navbar-item">
            <span class="icon"><i class="mdi mdi-email"></i></span>
            <span>Messages</span>
          </a>
          <hr class="navbar-divider">
          <a class="navbar-item">
            <span class="icon"><i class="mdi mdi-logout"></i></span>
            <span>Log Out</span>
          </a>
        </div>
      </div>
      <a href="https://justboil.me/tailwind-admin-templates/free-dashboard/" class="navbar-item has-divider desktop-icon-only">
        <span class="icon"><i class="mdi mdi-help-circle-outline"></i></span>
        <span>About</span>
      </a>
      <%= link_to root_path, title: t('views.admin.back'), class: "navbar-item has-divider desktop-icon-only" do %>
        <span class="icon"><i class="mdi mdi-backburger"></i></span>
        <span><%= t('views.admin.back') %></span>
      <% end %>
      <%= link_to destroy_user_session_path, method: :delete, title: t('devise.navbar.sign_out'),
                  class: 'navbar-item desktop-icon-only', turbo_frame: '_top',
                  data: { turbo_method: :delete, turbo_confirm: t('devise.sessions.sure') } do %>
        <span class="icon"><i class="mdi mdi-logout"></i></span>
        <span><%= t('devise.navbar.sign_out') %></span>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/header/_navbar.html.erb
<nav id="navbar-main" class="navbar is-fixed-top">
  <div class="navbar-brand">
    <a class="navbar-item mobile-aside-button">
      <span class="icon"><i class="mdi mdi-forwardburger mdi-24px"></i></span>
    </a>
    <div class="navbar-item">
      <div class="control"><input placeholder="Search everywhere..." class="input"></div>
    </div>
  </div>
  <div class="navbar-brand is-right">
    <a class="navbar-item --jb-navbar-menu-toggle" data-target="navbar-menu">
      <span class="icon"><i class="mdi mdi-dots-vertical mdi-24px"></i></span>
    </a>
  </div>
  <div class="navbar-menu" id="navbar-menu">
    <div class="navbar-end">
      <div class="navbar-item dropdown has-divider">
        <a class="navbar-link">
          <span class="icon"><i class="mdi mdi-menu"></i></span>
          <span>Sample Menu</span>
          <span class="icon">
            <i class="mdi mdi-chevron-down"></i>
          </span>
        </a>
        <div class="navbar-dropdown">
          <a href="profile.html" class="navbar-item">
            <span class="icon"><i class="mdi mdi-account"></i></span>
            <span>My Profile</span>
          </a>
          <a class="navbar-item">
            <span class="icon"><i class="mdi mdi-settings"></i></span>
            <span>Settings</span>
          </a>
          <a class="navbar-item">
            <span class="icon"><i class="mdi mdi-email"></i></span>
            <span>Messages</span>
          </a>
          <hr class="navbar-divider">
          <%= link_to destroy_user_session_path, method: :delete,
                      title: t('devise.navbar.sign_out'), class: 'navbar-item', turbo_frame: '_top',
                      data: { turbo_method: :delete, turbo_confirm: t('devise.sessions.sure') } do %>
            <span class="icon"><i class="mdi mdi-logout"></i></span>
            <span><%= t('devise.navbar.sign_out') %></span>
          <% end %>
        </div>
      </div>
      <div class="navbar-item dropdown has-divider has-user-avatar">
        <a class="navbar-link">
          <div class="user-avatar">
            <% if current_user.avatar.present? %>
              <%= image_tag current_user.avatar_thumb, class: "rounded-full",
                            alt: "#{current_user.first_name} #{current_user.last_name}" %>
            <% else %>
              <%= image_tag 'no-one.png', class: "rounded-full",
                            alt: "#{current_user.first_name} #{current_user.last_name}" %>
            <% end %>
          </div>
          <div class="is-user-name"><span>
            <%="#{current_user.first_name} #{current_user.last_name}" %>
          </span></div>
          <span class="icon"><i class="mdi mdi-chevron-down"></i></span>
        </a>
        <div class="navbar-dropdown">
          <a href="profile.html" class="navbar-item">
            <span class="icon"><i class="mdi mdi-account"></i></span>
            <span>My Profile</span>
          </a>
          <a class="navbar-item">
            <span class="icon"><i class="mdi mdi-settings"></i></span>
            <span>Settings</span>
          </a>
          <a class="navbar-item">
            <span class="icon"><i class="mdi mdi-email"></i></span>
            <span>Messages</span>
          </a>
          <hr class="navbar-divider">
          <a class="navbar-item">
            <span class="icon"><i class="mdi mdi-logout"></i></span>
            <span>Log Out</span>
          </a>
        </div>
      </div>
      <a href="https://justboil.me/tailwind-admin-templates/free-dashboard/" class="navbar-item has-divider desktop-icon-only">
        <span class="icon"><i class="mdi mdi-help-circle-outline"></i></span>
        <span>About</span>
      </a>
      <% if user_policy.admin_access? %>
        <%= link_to admin_root_path, title: t('views.admin.title'), class: "navbar-item has-divider desktop-icon-only" do %>
          <span class="icon"><i class="mdi mdi-database-cog-outline"></i></span>
          <span><%= t('views.admin.title') %></span>
        <% end %>
      <% end %>
      <%= link_to destroy_user_session_path, method: :delete, title: t('devise.navbar.sign_out'),
                  class: 'navbar-item desktop-icon-only', turbo_frame: '_top',
                  data: { turbo_method: :delete, turbo_confirm: t('devise.sessions.sure') } do %>
        <span class="icon"><i class="mdi mdi-logout"></i></span>
        <span><%= t('devise.navbar.sign_out') %></span>
      <% end %>
    </div>
  </div>
</nav>