config/routes.rb
Rails.application.routes.draw do
  resources :series
  resources :ebooks
  require 'sidekiq/web'

  authenticate :user, ->(user) { user.admin_role? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  namespace :admin do
    #get "dashboard", to: "dashboard#index"
    resources :publishers
    resources :users
    resources :categories do
      post :move, on: :member
      get :cancel, on: :member
      get :item, on: :member
    end
    root to: 'dashboard#index'
  end

  get '/profil', to: 'users#profile', as: :profile
  devise_for :users
  resources :users, only: %i(update) do
    patch :update_password, on: :member
  end

  resources :publishers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  resources :language, only: [:index, :show]
  resources :authors
  # Defines the root path route ("/")
  root to: 'home#index'
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :set_series, only: %i[ show edit update destroy ]
  before_action :authorize_series!, only: %i[show edit update destroy]
  before_action :authorize_series_class!, only: %i[index new create]

  def index
    authorize Series
    @series = Series.all
    @series = @series.search(params[:query]) if params[:query].present?
    @series = @series.ordered_by(params[:order], params[:direction]).page(params[:page]).per(per_page).decorate
    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def show
  end

  def create
    creator = SeriesServices::Creator.call(series_params)
    if creator.success?
      @series = creator.result.decorate
      respond_to do |format|
        format.html { redirect_to series_index_path, notice: t('views.series.create_success') }
        format.turbo_stream do
          if Series.all.count == 1
            @series = Series.all.ordered_by(params[:order], params[:direction]).page(params[:page]).per(per_page).decorate
          end
        end
      end
    else
      @errors = creator.errors
      @series = creator.result
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
        format.turbo_stream
      end
    end
  end

  # GET /series/new
  def new
    @series = Series.new
    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  # GET /series/1/edit
  def edit
  end

  def update
    updator = SeriesServices::Updator.call(params[:id], series_params)
    if updator.success?
      @series = updator.result.decorate
      respond_to do |format|
        format.html { redirect_to series_index_path, notice: t('views.series.update_success') }
        format.turbo_stream
      end
    else
      @errors = updator.errors
      respond_to do |format|
        @series = Series.find(params[:id])
        format.html {
          flash.now[:alert] = @errors.values.flatten.join(", ")
          render :edit, status: :unprocessable_entity
        }
        format.turbo_stream
      end
    end
  end

  def destroy
    @series = Series.find(params[:id])
    @series.destroy!

    respond_to do |format|
      format.html { redirect_to series_index_path, status: :see_other, notice: t('views.series.destroy_success') }
      format.turbo_stream
    end
  end

  private
    def authorize_series!
      authorize @series
    end

    def authorize_series_class!
      authorize Series
    end

    def set_series
      @series = Series.find(params.expect(:id))
    end

    def series_params
      params.require(:series).permit(:title, :subtitle, :short_content, :content, :video, :isbn, :active)
    end

    def per_page
      params[:per_page] || SeriesDecorator::PER_PAGES_DEFAULT
    end
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/series/_errors.html.erb
<% if errors.present? %>
  <div class="notification red" data-dismiss-target="notification" data-controller="dismiss">
    <div class="flex flex-col md:flex-row items-center justify-between space-y-3 md:space-y-0">
      <div>
        <ul>
          <% errors.keys.each do |attribute| %>
            <% if errors[attribute].any? %>
              <li>
                <strong><%= t("views.series.errors.#{attribute.to_s}") %>:</strong>
                <% errors[attribute].each do |message| %>
                  <ul>
                    <li><%= message %></li>
                  </ul>
                <% end %>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
      <%= button_tag t('helpers.submit.close'), type: "button", class: "button small textual",
        data: { action: "dismiss#dismiss" } %>
    </div>
  </div>
<% end %>

app/views/series/_form.html.erb
<%= turbo_frame_tag 'series_notice' %>
<section class="section main-section" data-controller="fade-out" data-fade-out-target="frame" data-auto-fade-out-target="frame">
  <div class="card mb-6">
    <header class="card-header">
      <p class="card-header-title">
        <span class="icon"><i class="mdi mdi-ballot"></i></span>
        <%= @series.persisted? ? t('views.series.edit.title') : t('views.series.new.title') %>
      </p>
    </header>
    <div class="card-content">
      <%= turbo_frame_tag 'series_errors' do %>
        <%= render partial: 'series/errors', locals: { errors: @errors } if @errors.present? %>
      <% end %>
      <%= form_with model: @series, url: @series.persisted? ? series_path(@series) : series_index_path,
                    data: { turbo: @turbo_request } do |f| %>
        <div class="field">
          <%= f.label :title, class: "label required" %>
          <div class="control">
            <%= f.text_field :title, class: "input", placeholder: t('activerecord.attributes.series.title'), required: true %>
          </div>
        </div>
        <div class="field">
          <%= f.label :isbn, class: "label required" %>
          <div class="control">
            <%= f.text_field :isbn, class: "input", placeholder: t('activerecord.attributes.series.isbn'), required: true %>
          </div>
        </div>
        <div class="field">
          <%= f.label :active, class: "label" %>
          <div class="control">
            <%= f.check_box :active, class: "checkbox" %>
          </div>
        </div>
        <div class="field">
          <%= f.label :subtitle, class: "label required" %>
          <div class="control">
            <%= f.text_field :subtitle, class: "input", placeholder: t('activerecord.attributes.series.subtitle'), required: true  %>
          </div>
        </div>

        <div class="field">
          <%= f.label :video, class: "label" %>
          <div class="control">
            <%= f.text_field :video, class: "input", placeholder: t('activerecord.attributes.series.subtitle')  %>
          </div>
        </div>

        <div class="field">
          <%= f.label :short_content, class: "label required" %>
          <div class="control">
            <%= f.rich_text_area :short_content, class: "textarea", required: true ,
              placeholder: t('activerecord.attributes.series.short_content'), data: { controller: 'trix' } %>
          </div>
        </div>

        <div class="field">
          <%= f.label :content, class: "label required" %>
          <div class="control">
            <%= f.rich_text_area :content, class: "textarea", required: true ,
              placeholder: t('activerecord.attributes.series.content'), data: { controller: 'trix' } %>
          </div>
        </div>

        <hr>

        <div class="field grouped">
          <div class="control">
            <%= f.submit @series.persisted? ? t('views.series.edit.submit') : t('views.series.new.submit'), class: "button green" %>
          </div>
          <div class="control">
            <% if @turbo_request %>
              <%= button_tag t('helpers.submit.cancel'), type: "reset", class: "button",
                             data: { action: "fade-out#remove" } %>
            <% else %>
              <%= link_to t('helpers.submit.cancel'), series_index_path, class: "button", data: { turbo_frame: "_top" } %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/series/_index.html.erb
<div class="card has-table">
  <header class="card-header">
    <p class="card-header-title">
      <span class="icon"><i class="mdi mdi-account-multiple"></i></span><%= t('views.series.title') %>
      &nbsp;&nbsp;
      <%= link_to new_series_path, class: "button small blue", title: t('views.series.new_button'),
                  data: { turbo_frame: "series_form", turbo_stream: 'update' } do %>
        <span class="icon"><i class="mdi mdi-plus"></i></span>
      <% end %>
    </p>
    <%= form_with url: series_index_path, method: :get,
                  data: { controller: 'search-form', turbo_frame: 'result', turbo_stream: 'update' },
                  class: "control has-icons-left" do |f| %>
      <div class="field">
        <div class="field-body">
          <div class="field">
            <div class="control icons-left">
              <%= f.text_field :query, placeholder: t('helpers.placeholder.search'), class: "input",
                               data: { "search-form-target": 'input', action: 'keyup->search-form#handleKeyup' } %>
              <span class="icon left"><i class="mdi mdi-magnify"></i></span>
            </div>
          </div>
        </div>
      </div>
    <% end %>

    <a href="#" class="card-header-icon">
      <span class="icon"><i class="mdi mdi-reload"></i></span>
    </a>
  </header>
  <div class="card-content">
    <%= turbo_frame_tag 'results' do %>
      <%= render partial: 'series/series_list' %>
    <% end %>
  </div>
</div>

app/views/series/_series.html.erb
<tr id="series_<%= series.id %>" class="<%= 'highlight' if local_assigns[:highlight] %>">
  <%= render partial: 'series/series_items', locals: { series: series } %>
</tr>

app/views/series/_series_items.html.erb
<td data-label="title"><%= series.title %></td>
<td data-label="subtitle"><%= series.subtitle %></td>
<td data-label="isbn"><%= series.isbn %></td>
<td data-label="active">
  <%= content_tag(:i, "", class: "mdi #{series.active ? 'mdi-check-circle text-green-500' : 'mdi-close-circle text-red-500'}") %>
</td>
<td data-label="imported">
  <%= content_tag(:i, "", class: "mdi #{series.imported ? 'mdi-check-circle text-green-500' : 'mdi-close-circle text-red-500'}") %>
</td>
<td data-label="checked">
  <%= content_tag(:i, "", class: "mdi #{series.checked ? 'mdi-check-circle text-green-500' : 'mdi-close-circle text-red-500'}") %>
</td>
<td data-label="ebooks"><%= series.ebooks.count %></td>
<td class="actions-cell">
  <div class="buttons right nowrap">
    <button class="button small blue --jb-modal"  data-target="sample-modal-2" type="button">
      <span class="icon"><i class="mdi mdi-eye"></i></span>
    </button>
    <%= link_to edit_series_path(series), class: "button small green", title: t('views.series.edit_button'),
                data: { turbo_frame: "series_form", turbo_stream: 'update' } do %>
      <span class="icon"><i class="mdi mdi-pencil"></i></span>
    <% end %>
    <%= button_tag type: 'button', class: 'button small red',
                   data: { controller: "modal", action: "click->modal#open",
                           target: "modal-destroy", destroy_url: series_path(series),
                           question_text: t('views.series.destroy_modal.text', name: series.title)
                   } do %>
      <span class="icon"><i class="mdi mdi-trash-can"></i></span>
    <% end unless series.imported %>
  </div>
</td>

app/views/series/_series_list.html.erb
<% if @series.any? %>
  <%= paginate @series %>
  <table>
    <thead>
    <tr>
      <th><%= series_sort_link('title', t('activerecord.attributes.series.title')) %></th>
      <th><%= series_sort_link('subtitle', t('activerecord.attributes.series.subtitle')) %></th>
      <th><%= series_sort_link('isbn', t('activerecord.attributes.series.isbn')) %></th>
      <th><%= series_sort_link('active', t('activerecord.attributes.series.active')) %></th>
      <th><%= series_sort_link('imported', t('activerecord.attributes.series.imported')) %></th>
      <th><%= series_sort_link('checked', t('activerecord.attributes.series.checked')) %></th>
      <th><%= t('activerecord.attributes.series.ebook_count') %></th>
      <th></th>
    </tr>
    </thead>
    <tbody id="series-list">
    <% @series.each do |series| %>
      <%= render partial: 'series/series', locals: { series: series } %>
    <% end %>
    </tbody>
  </table>
  <%= paginate @series %>
<% else %>
  <p class="padding-10"><%= t('views.series.not_found') %></p>
<% end %>

app/views/series/create.turbo_stream.erb
<% if @errors.present? %>
  <%= turbo_stream.update 'series_errors', partial: 'series/errors', locals: { errors: @errors } %>
<% else %>
  <%= turbo_stream.update "series_notice", partial: 'shared/notice', locals: { notice: t('views.series.create_success') } %>
  <%= turbo_stream.prepend "series_notice" do %>
    <div data-controller="auto-fade-out" ></div>
  <% end %>
  <% if Series.all.count == 1 %>
    <%= turbo_stream.update 'results', partial: 'series/series_list' %>
  <% else %>
    <%= turbo_stream.prepend "series-list" do %>
      <%= render @series, highlight: true %>
    <% end %>
  <% end %>

<% end %>

app/views/series/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@series) %>
<%= turbo_stream.update "series_notice", partial: 'shared/notice',
   locals: { notice: t('views.series.destroy_success') } %>

app/views/series/edit.html.erb
<%= render 'layouts/header/navbar' %>
<%= render 'layouts/aside/nav' %>
<section class="is-hero-bar">
  <div class="flex flex-col md:flex-row items-center justify-between space-y-6 md:space-y-0">
    <h1 class="title"><%= t('views.series.title') %></h1>
  </div>
</section>
<section class="section main-section">
  <%= turbo_frame_tag "series_form" do %>
    <%= render partial: 'series/form' %>
  <% end %>
</section>

app/views/series/edit.turbo_stream.erb
<%= turbo_stream.update 'series_form', partial: 'series/form' %>

app/views/series/index.html.erb
<%= render 'layouts/header/navbar' %>
<%= render 'layouts/aside/nav' %>
<section class="is-hero-bar">
  <div class="flex flex-col md:flex-row items-center justify-between space-y-6 md:space-y-0">
    <h1 class="title"><%= t('views.series.title') %></h1>
  </div>
</section>
<section class="section main-section">
  <%= turbo_frame_tag "series_form", data: { fade_out_target: "frame" } %>
  <%= render 'series/index' %>
</section>
<%= render 'modals/destroy_modal' %>

app/views/series/index.turbo_stream.erb
<%= turbo_stream.update 'results', partial: 'series/series_list' %>

app/views/series/show.html.erb
<% content_for :title, "Showing series" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing series</h1>

  <%= render @series %>

  <%= link_to "Edit this series", edit_series_path(@series), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to series", series_index_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <div class="sm:inline-block mt-2 sm:mt-0 sm:ml-2">
    <%= button_to "Destroy this series", @series, method: :delete, class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
  </div>
</div>

app/views/series/update.turbo_stream.erb
<% if @errors.present? %>
  <%= turbo_stream.update 'series_errors', partial: 'series/errors', locals: { errors: @errors } %>
<% else %>
  <%= turbo_stream.update "series_notice", partial: 'shared/notice', locals: { notice: t('views.series.update_success') } %>
  <%= turbo_stream.prepend "series_notice" do %>
    <div data-controller="auto-fade-out" ></div>
  <% end %>
  <%= turbo_stream.update "series_#{@series.id}" do %>
    <%= render partial: 'series/series_items', locals: { series: @series }, highlight: true %>
  <% end %>
<% end %>